name: Name
title: Marketing Skeleton
description: >- # this means to ignore newlines until the next yaml key
  Lorem Ipsum.
color: "#ffffff"
background_color: "#000000"
logo: "assets/img/logo.png"
apple_mask_icon: "assets/img/apple-mask-icon.svg"
themed_mask_icon: "assets/img/themed-mask-icon.svg"
sharing_image: "assets/img/example2.png"
twitter: "@mechstack"
